import type { Technology } from '../interfaces';

export const TECH_CATEGORIES = [
  'Programming Languages',
  'Frontend Development',
  'Backend Development',
  'Mobile App Development',
  'AI/ML',
  'Database',
  'Data Visualization',
  'Devops',
  'Backend as a Service(BaaS)',
  'Framework',
  'Testing',
  'Software',
  'Static Site Generators',
  'Game Engines',
  'Automation',
  'Other',
];

export const technologies: Technology[] = [
  // * Programming Languages
  {
    id: 'c',
    name: 'C',
    category: 'Programming Languages',
    svgPath: '/icons/ProgrammingLanguages/c.svg',
  },
  {
    id: 'clojure',
    name: 'Clojure',
    category: 'Programming Languages',
    svgPath: '/icons/ProgrammingLanguages/clojure.svg',
  },
  {
    id: 'coffeescript',
    name: 'Coffeescript',
    category: 'Programming Languages',
    svgPath: '/icons/ProgrammingLanguages/coffeescript.svg',
  },
  {
    id: 'cpp',
    name: 'C++',
    category: 'Programming Languages',
    svgPath: '/icons/ProgrammingLanguages/cpp.svg',
  },
  {
    id: 'csharp',
    name: 'C#',
    category: 'Programming Languages',
    svgPath: '/icons/ProgrammingLanguages/csharp.svg',
  },
  {
    id: 'elixir',
    name: 'Elixir',
    category: 'Programming Languages',
    svgPath: '/icons/ProgrammingLanguages/elixir.svg',
  },
  {
    id: 'erlang',
    name: 'Erlang',
    category: 'Programming Languages',
    svgPath: '/icons/ProgrammingLanguages/erlang.svg',
  },
  {
    id: 'go',
    name: 'Go',
    category: 'Programming Languages',
    svgPath: '/icons/ProgrammingLanguages/go.svg',
  },
  {
    id: 'haskell',
    name: 'Haskell',
    category: 'Programming Languages',
    svgPath: '/icons/ProgrammingLanguages/haskell.svg',
  },
  {
    id: 'java',
    name: 'Java',
    category: 'Programming Languages',
    svgPath: '/icons/ProgrammingLanguages/java.svg',
  },
  {
    id: 'js',
    name: 'JavaScript',
    category: 'Programming Languages',
    svgPath: '/icons/ProgrammingLanguages/javascript.svg',
  },
  {
    id: 'objectivec',
    name: 'Objectivec',
    category: 'Programming Languages',
    svgPath: '/icons/ProgrammingLanguages/objectivec.svg',
  },
  {
    id: 'perl',
    name: 'Perl',
    category: 'Programming Languages',
    svgPath: '/icons/ProgrammingLanguages/perl.svg',
  },
  {
    id: 'php',
    name: 'Php',
    category: 'Programming Languages',
    svgPath: '/icons/ProgrammingLanguages/php.svg',
  },
  {
    id: 'ruby',
    name: 'Ruby',
    category: 'Programming Languages',
    svgPath: '/icons/ProgrammingLanguages/ruby.svg',
  },
  {
    id: 'rust',
    name: 'Rust',
    category: 'Programming Languages',
    svgPath: '/icons/ProgrammingLanguages/rust.svg',
  },
  {
    id: 'scala',
    name: 'Scala',
    category: 'Programming Languages',
    svgPath: '/icons/ProgrammingLanguages/scala.svg',
  },
  {
    id: 'swift',
    name: 'Swift',
    category: 'Programming Languages',
    svgPath: '/icons/ProgrammingLanguages/swift.svg',
  },
  {
    id: 'ts',
    name: 'TypeScript',
    category: 'Programming Languages',
    svgPath: '/icons/ProgrammingLanguages/typescript.svg',
  },
  {
    id: 'python',
    name: 'Python',
    category: 'Programming Languages',
    svgPath: '/icons/ProgrammingLanguages/python.svg',
  },
  // * Frontend
  {
    id: 'react',
    name: 'React',
    category: 'Frontend Development',
    svgPath: '/icons/FrontendDevelopment/reactjs.svg',
  },
  {
    id: 'vue',
    name: 'Vue.js',
    category: 'Frontend Development',
    svgPath: '/icons/FrontendDevelopment/vuejs.svg',
  },
  {
    id: 'babel',
    name: 'Babel',
    category: 'Frontend Development',
    svgPath: '/icons/FrontendDevelopment/babel.svg',
  },
  {
    id: 'backbonejs',
    name: 'Backbonejs',
    category: 'Frontend Development',
    svgPath: '/icons/FrontendDevelopment/backbonejs.svg',
  },
  {
    id: 'bootstrap',
    name: 'Bootstrap',
    category: 'Frontend Development',
    svgPath: '/icons/FrontendDevelopment/bootstrap.svg',
  },
  {
    id: 'bulma',
    name: 'Bulma',
    category: 'Frontend Development',
    svgPath: '/icons/FrontendDevelopment/bulma.svg',
  },
  {
    id: 'css',
    name: 'Css',
    category: 'Frontend Development',
    svgPath: '/icons/FrontendDevelopment/css.svg',
  },
  {
    id: 'ember',
    name: 'Ember',
    category: 'Frontend Development',
    svgPath: '/icons/FrontendDevelopment/ember.svg',
  },
  {
    id: 'gtk',
    name: 'Gtk',
    category: 'Frontend Development',
    svgPath: '/icons/FrontendDevelopment/gtk.svg',
  },
  {
    id: 'gulp',
    name: 'Gulp',
    category: 'Frontend Development',
    svgPath: '/icons/FrontendDevelopment/gulp.svg',
  },
  {
    id: 'html',
    name: 'HTML',
    category: 'Frontend Development',
    svgPath: '/icons/FrontendDevelopment/html.svg',
  },
  {
    id: 'materialize',
    name: 'Materialize',
    category: 'Frontend Development',
    svgPath: '/icons/FrontendDevelopment/materialize.svg',
  },
  {
    id: 'meteor',
    name: 'Meteor',
    category: 'Frontend Development',
    svgPath: '/icons/FrontendDevelopment/meteor.svg',
  },
  {
    id: 'pug',
    name: 'Pug',
    category: 'Frontend Development',
    svgPath: '/icons/FrontendDevelopment/pug.svg',
  },
  {
    id: 'qt',
    name: 'Qt',
    category: 'Frontend Development',
    svgPath: '/icons/FrontendDevelopment/qt.svg',
  },
  {
    id: 'redux',
    name: 'Redux',
    category: 'Frontend Development',
    svgPath: '/icons/FrontendDevelopment/redux.svg',
  },
  {
    id: 'sass',
    name: 'Sass',
    category: 'Frontend Development',
    svgPath: '/icons/FrontendDevelopment/sass.svg',
  },
  {
    id: 'svelte',
    name: 'Svelte',
    category: 'Frontend Development',
    svgPath: '/icons/FrontendDevelopment/svelte.svg',
  },
  {
    id: 'tailwind',
    name: 'Tailwind',
    category: 'Frontend Development',
    svgPath: '/icons/FrontendDevelopment/tailwind.svg',
  },
  {
    id: 'vuetify',
    name: 'Vuetify',
    category: 'Frontend Development',
    svgPath: '/icons/FrontendDevelopment/vuetify.svg',
  },
  {
    id: 'webpack',
    name: 'Webpack',
    category: 'Frontend Development',
    svgPath: '/icons/FrontendDevelopment/webpack.svg',
  },
  {
    id: 'wxwidgets',
    name: 'Wxwidgets',
    category: 'Frontend Development',
    svgPath: '/icons/FrontendDevelopment/wxwidgets.svg',
  },
  // * Backend
  {
    id: 'express',
    name: 'Express',
    category: 'Backend Development',
    svgPath: '/icons/BackendDevelopment/express.svg',
  },
  {
    id: 'graphql',
    name: 'Graphql',
    category: 'Backend Development',
    svgPath: '/icons/BackendDevelopment/graphql.svg',
  },
  {
    id: 'hadoop',
    name: 'Hadoop',
    category: 'Backend Development',
    svgPath: '/icons/BackendDevelopment/hadoop.svg',
  },
  {
    id: 'kafka',
    name: 'Kafka',
    category: 'Backend Development',
    svgPath: '/icons/BackendDevelopment/kafka.svg',
  },
  {
    id: 'nestjs',
    name: 'Nestjs',
    category: 'Backend Development',
    svgPath: '/icons/BackendDevelopment/nestjs.svg',
  },
  {
    id: 'nodejs',
    name: 'Nodejs',
    category: 'Backend Development',
    svgPath: '/icons/BackendDevelopment/nodejs.svg',
  },
  {
    id: 'openresty',
    name: 'Openresty',
    category: 'Backend Development',
    svgPath: '/icons/BackendDevelopment/openresty.svg',
  },
  {
    id: 'rabbitmq',
    name: 'Rabbitmq',
    category: 'Backend Development',
    svgPath: '/icons/BackendDevelopment/rabbitmq.svg',
  },
  {
    id: 'solr',
    name: 'Solr',
    category: 'Backend Development',
    svgPath: '/icons/BackendDevelopment/solr.svg',
  },
  {
    id: 'spring',
    name: 'Spring',
    category: 'Backend Development',
    svgPath: '/icons/BackendDevelopment/spring.svg',
  },
  // * Data Base
  {
    id: 'cassandra',
    name: 'Cassandra',
    category: 'Data Base',
    svgPath: '/icons/Database/cassandra.svg',
  },
  {
    id: 'cockroachdb',
    name: 'Cockroachdb',
    category: 'Data Base',
    svgPath: '/icons/Database/cockroachdb.svg',
  },
  {
    id: 'couchdb',
    name: 'Couchdb',
    category: 'Data Base',
    svgPath: '/icons/Database/couchdb.svg',
  },
  {
    id: 'elasticsearch',
    name: 'Elasticsearch',
    category: 'Data Base',
    svgPath: '/icons/Database/elasticsearch.svg',
  },
  {
    id: 'hive',
    name: 'Hive',
    category: 'Data Base',
    svgPath: '/icons/Database/hive.svg',
  },
  {
    id: 'mariadb',
    name: 'Mariadb',
    category: 'Data Base',
    svgPath: '/icons/Database/mariadb.svg',
  },
  {
    id: 'mongodb',
    name: 'Mongodb',
    category: 'Data Base',
    svgPath: '/icons/Database/mongodb.svg',
  },
  {
    id: 'mysql',
    name: 'Mysql',
    category: 'Data Base',
    svgPath: '/icons/Database/mysql.svg',
  },
  {
    id: 'oracle',
    name: 'Oracle',
    category: 'Data Base',
    svgPath: '/icons/Database/oracle.svg',
  },
  {
    id: 'postgresql',
    name: 'Postgresql',
    category: 'Data Base',
    svgPath: '/icons/Database/postgresql.svg',
  },
  {
    id: 'realm',
    name: 'Realm',
    category: 'Data Base',
    svgPath: '/icons/Database/realm.svg',
  },
  {
    id: 'redis',
    name: 'Redis',
    category: 'Data Base',
    svgPath: '/icons/Database/redis.svg',
  },
  {
    id: 'sqlite',
    name: 'Sqlite',
    category: 'Data Base',
    svgPath: '/icons/Database/sqlite.svg',
  },
  // * Mobile App Development
  {
    id: 'android',
    name: 'Android',
    category: 'Mobile App Development',
    svgPath: '/icons/MobileAppDevelopment/android.svg',
  },
  {
    id: 'apachecordova',
    name: 'Apachecordova',
    category: 'Mobile App Development',
    svgPath: '/icons/MobileAppDevelopment/apachecordova.svg',
  },
  {
    id: 'dart',
    name: 'Dart',
    category: 'Mobile App Development',
    svgPath: '/icons/MobileAppDevelopment/dart.svg',
  },
  {
    id: 'flutter',
    name: 'Flutter',
    category: 'Mobile App Development',
    svgPath: '/icons/MobileAppDevelopment/flutter.svg',
  },
  {
    id: 'ionic',
    name: 'Ionic',
    category: 'Mobile App Development',
    svgPath: '/icons/MobileAppDevelopment/ionic.svg',
  },
  {
    id: 'kotlin',
    name: 'Kotlin',
    category: 'Mobile App Development',
    svgPath: '/icons/MobileAppDevelopment/kotlin.svg',
  },
  {
    id: 'nativescript',
    name: 'Nativescript',
    category: 'Mobile App Development',
    svgPath: '/icons/MobileAppDevelopment/nativescript.svg',
  },
  {
    id: 'reactnative',
    name: 'React Native',
    category: 'Mobile App Development',
    svgPath: '/icons/MobileAppDevelopment/reactnative.svg',
  },
  {
    id: 'xamarin',
    name: 'Xamarin',
    category: 'Mobile App Development',
    svgPath: '/icons/MobileAppDevelopment/xamarin.svg',
  },
  // * BaaS
  {
    id: 'amplify',
    name: 'Amplify',
    category: 'BaaS',
    svgPath: '/icons/BaaS/amplify.svg',
  },
  {
    id: 'firebase',
    name: 'Firebase',
    category: 'BaaS',
    svgPath: '/icons/BaaS/firebase.svg',
  },
  {
    id: 'heroku',
    name: 'Heroku',
    category: 'BaaS',
    svgPath: '/icons/BaaS/heroku.svg',
  },
  // * AIML
  {
    id: 'opencv',
    name: 'Opencv',
    category: 'AIML',
    svgPath: '/icons/AIML/opencv.svg',
  },
  {
    id: 'pytorch',
    name: 'Pytorch',
    category: 'AIML',
    svgPath: '/icons/AIML/pytorch.svg',
  },
  {
    id: 'scikit',
    name: 'Scikit',
    category: 'AIML',
    svgPath: '/icons/AIML/scikit.svg',
  },
  {
    id: 'tensorflow',
    name: 'Tensorflow',
    category: 'AIML',
    svgPath: '/icons/AIML/tensorflow.svg',
  },
  // * Automation
  {
    id: 'ifttt',
    name: 'Ifttt',
    category: 'Automation',
    svgPath: '/icons/Automation/ifttt.svg',
  },
  {
    id: 'zapier',
    name: 'Zapier',
    category: 'Automation',
    svgPath: '/icons/Automation/zapier.svg',
  },
  // * Data Visualization
  {
    id: 'canvasjs',
    name: 'Canvasjs',
    category: 'DataVisualization',
    svgPath: '/icons/DataVisualization/canvasjs.svg',
  },
  {
    id: 'chartjs',
    name: 'Chartjs',
    category: 'DataVisualization',
    svgPath: '/icons/DataVisualization/chartjs.svg',
  },
  {
    id: 'd3js',
    name: 'D3js',
    category: 'DataVisualization',
    svgPath: '/icons/DataVisualization/d3js.svg',
  },
  {
    id: 'grafana',
    name: 'Grafana',
    category: 'DataVisualization',
    svgPath: '/icons/DataVisualization/grafana.svg',
  },
  {
    id: 'kibana',
    name: 'Kibana',
    category: 'DataVisualization',
    svgPath: '/icons/DataVisualization/kibana.svg',
  },
  // * Devops
  {
    id: 'aws',
    name: 'Aws',
    category: 'Devops',
    svgPath: '/icons/Devops/aws.svg',
  },
  {
    id: 'azure',
    name: 'Azure',
    category: 'Devops',
    svgPath: '/icons/Devops/azure.svg',
  },
  {
    id: 'bash',
    name: 'Bash',
    category: 'Devops',
    svgPath: '/icons/Devops/bash.svg',
  },
  {
    id: 'circleci',
    name: 'Circleci',
    category: 'Devops',
    svgPath: '/icons/Devops/circleci.svg',
  },
  {
    id: 'docker',
    name: 'Docker',
    category: 'Devops',
    svgPath: '/icons/Devops/docker.svg',
  },
  {
    id: 'gcp',
    name: 'Gcp',
    category: 'Devops',
    svgPath: '/icons/Devops/gcp.svg',
  },
  {
    id: 'jenkins',
    name: 'Jenkins',
    category: 'Devops',
    svgPath: '/icons/Devops/jenkins.svg',
  },
  {
    id: 'kubernetes',
    name: 'Kubernetes',
    category: 'Devops',
    svgPath: '/icons/Devops/kubernetes.svg',
  },
  {
    id: 'travisci',
    name: 'Travisci',
    category: 'Devops',
    svgPath: '/icons/Devops/travisci.svg',
  },
  {
    id: 'vagrant',
    name: 'Vagrant',
    category: 'Devops',
    svgPath: '/icons/Devops/vagrant.svg',
  },
  // * Framework
  {
    id: 'codeigniter',
    name: 'Codeigniter',
    category: 'Framework',
    svgPath: '/icons/Framework/codeigniter.svg',
  },
  {
    id: 'django',
    name: 'Django',
    category: 'Framework',
    svgPath: '/icons/Framework/django.svg',
  },
  {
    id: 'dotnet',
    name: 'Dotnet',
    category: 'Framework',
    svgPath: '/icons/Framework/dotnet.svg',
  },
  {
    id: 'electron',
    name: 'Electron',
    category: 'Framework',
    svgPath: '/icons/Framework/electron.svg',
  },
  {
    id: 'flask',
    name: 'Flask',
    category: 'Framework',
    svgPath: '/icons/Framework/flask.svg',
  },
  {
    id: 'laravel',
    name: 'Laravel',
    category: 'Framework',
    svgPath: '/icons/Framework/laravel.svg',
  },
  {
    id: 'Quasar',
    name: 'Quasar',
    category: 'Framework',
    svgPath: '/icons/Framework/quasar.svg',
  },
  {
    id: 'rails',
    name: 'Rails',
    category: 'Framework',
    svgPath: '/icons/Framework/rails.svg',
  },
  {
    id: 'symfony',
    name: 'Symfony',
    category: 'Framework',
    svgPath: '/icons/Framework/symfony.svg',
  },
  // * Testing
  {
    id: 'cypress',
    name: 'Cypress',
    category: 'Testing',
    svgPath: '/icons/Testing/cypress.svg',
  },
  {
    id: 'jasmine',
    name: 'Jasmine',
    category: 'Testing',
    svgPath: '/icons/Testing/jasmine.svg',
  },
  {
    id: 'jest',
    name: 'Jest',
    category: 'Testing',
    svgPath: '/icons/Testing/jest.svg',
  },
  {
    id: 'karma',
    name: 'Karma',
    category: 'Testing',
    svgPath: '/icons/Testing/karma.svg',
  },
  {
    id: 'mocha',
    name: 'Mocha',
    category: 'Testing',
    svgPath: '/icons/Testing/mocha.svg',
  },
  {
    id: 'puppeteer',
    name: 'Puppeteer',
    category: 'Testing',
    svgPath: '/icons/Testing/puppeteer.svg',
  },
  {
    id: 'selenium',
    name: 'Selenium',
    category: 'Testing',
    svgPath: '/icons/Testing/selenium.svg',
  },
  // * GameEngines
  {
    id: 'unity',
    name: 'Unity',
    category: 'GameEngines',
    svgPath: '/icons/GameEngines/unity.svg',
  },
  {
    id: 'unreal',
    name: 'Unreal',
    category: 'GameEngines',
    svgPath: '/icons/GameEngines/unreal.svg',
  },
  // * Software
  {
    id: 'blender',
    name: 'Blender',
    category: 'Software',
    svgPath: '/icons/Software/blender.svg',
  },
  {
    id: 'figma',
    name: 'Figma',
    category: 'Software',
    svgPath: '/icons/Software/figma.svg',
  },
  {
    id: 'framer',
    name: 'Framer',
    category: 'Software',
    svgPath: '/icons/Software/framer.svg',
  },
  {
    id: 'illustrator',
    name: 'Illustrator',
    category: 'Software',
    svgPath: '/icons/Software/illustrator.svg',
  },
  {
    id: 'invision',
    name: 'Invision',
    category: 'Software',
    svgPath: '/icons/Software/invision.svg',
  },
  {
    id: 'matlab',
    name: 'Matlab',
    category: 'Software',
    svgPath: '/icons/Software/matlab.svg',
  },
  {
    id: 'photoshop',
    name: 'Photoshop',
    category: 'Software',
    svgPath: '/icons/Software/photoshop.svg',
  },
  {
    id: 'postman',
    name: 'Postman',
    category: 'Software',
    svgPath: '/icons/Software/postman.svg',
  },
  {
    id: 'sketch',
    name: 'Sketch',
    category: 'Software',
    svgPath: '/icons/Software/sketch.svg',
  },
  {
    id: 'solidworks',
    name: 'Solidworks',
    category: 'Software',
    svgPath: '/icons/Software/solidworks.svg',
  },
  {
    id: 'xd',
    name: 'Xd',
    category: 'Software',
    svgPath: '/icons/Software/xd.svg',
  },
  // * Static Site Generators
  {
    id: '11ty',
    name: '11ty',
    category: 'StaticSiteGenerators',
    svgPath: '/icons/StaticSiteGenerators/11ty.svg',
  },
  {
    id: 'gatsby',
    name: 'Gatsby',
    category: 'StaticSiteGenerators',
    svgPath: '/icons/StaticSiteGenerators/gatsby.svg',
  },
  {
    id: 'gridsome',
    name: 'Gridsome',
    category: 'StaticSiteGenerators',
    svgPath: '/icons/StaticSiteGenerators/gridsome.svg',
  },
  {
    id: 'hexo',
    name: 'Hexo',
    category: 'StaticSiteGenerators',
    svgPath: '/icons/StaticSiteGenerators/hexo.svg',
  },
  {
    id: 'hugo',
    name: 'Hugo',
    category: 'StaticSiteGenerators',
    svgPath: '/icons/StaticSiteGenerators/hugo.svg',
  },
  {
    id: 'jekyll',
    name: 'Jekyll',
    category: 'StaticSiteGenerators',
    svgPath: '/icons/StaticSiteGenerators/jekyll.svg',
  },
  {
    id: 'middleman',
    name: 'Middleman',
    category: 'StaticSiteGenerators',
    svgPath: '/icons/StaticSiteGenerators/middleman.svg',
  },
  {
    id: 'nextjs',
    name: 'Nextjs',
    category: 'StaticSiteGenerators',
    svgPath: '/icons/StaticSiteGenerators/nextjs.svg',
  },
  {
    id: 'nuxtjs',
    name: 'Nuxtjs',
    category: 'StaticSiteGenerators',
    svgPath: '/icons/StaticSiteGenerators/nuxtjs.svg',
  },
  {
    id: 'sapper',
    name: 'sapper',
    category: 'StaticSiteGenerators',
    svgPath: '/icons/StaticSiteGenerators/sapper.svg',
  },
  {
    id: 'scully',
    name: 'scully',
    category: 'StaticSiteGenerators',
    svgPath: '/icons/StaticSiteGenerators/scully.svg',
  },
  {
    id: 'sculpin',
    name: 'Sculpin',
    category: 'StaticSiteGenerators',
    svgPath: '/icons/StaticSiteGenerators/sculpin.svg',
  },
  {
    id: 'vuepress',
    name: 'Vuepress',
    category: 'StaticSiteGenerators',
    svgPath: '/icons/StaticSiteGenerators/vuepress.svg',
  },
  // * Others
  {
    id: 'arduino',
    name: 'Arduino',
    category: 'Other',
    svgPath: '/icons/Other/arduino.svg',
  },
  {
    id: 'git',
    name: 'Git',
    category: 'Other',
    svgPath: '/icons/Other/git.svg',
  },
  {
    id: 'linux',
    name: 'Linux',
    category: 'Other',
    svgPath: '/icons/Other/linux.svg',
  },
];
